main: fun.nothaving.feature.Main
name: featureCreep
version: 0.0.1
author: Fruooop (MC MeatNugger)
api-version: 1.13
description: Basically a test plugin for testing concepts
commands:
    commandAbbreviation:
      description: Description of command
      usage: /<command> [Extra parameters (if applicable)]